### ISSUE TITLE
Module 6 -Enhance Built.io lab for accuracy/clarity

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-cloud-collab-issues#1]
Enhance Built.io lab for accuracy/clarity - verify the screenshots, and the flow.

**Comment by dstaudt** [comment]
Completed and published

**Comment by austinMarcos** [comment]
Ready to be published.  Austin H. should review for final QA.

**Comment by ObjectIsAdvantag** [comment]
I beleive we're good though David owns this part, he'll know for sure.
Assigning to @dstaudt

**Comment by dstaudt** [comment]
collab-spark-builtio-itp has been deactivated/obsoleted

Assigning to @klevenstein for closure
