### ISSUE TITLE
Update "Room" to "Space"

### ISSUE THREAD

**Issue by mercurypulse** [CiscoDevNet/devnet-express-cloud-collab-issues#10]
In step #7, the wording is now "Space ID". It has been updated even in Built.io.  Needs to be updated in the Learning Lab:

https://learninglabs.cisco.com/tracks/devnet-express-cloud-collab-it-pro/devnet-express-cloud-integration-itpro/collab-spark-builtio-itp/step/6

**Comment by dstaudt** [comment]
This lab is obsolete and has been deactivated...closing
