### ISSUE TITLE
Documentation problem - DevNet express CC for IT Pros Spark Extensibility

### ISSUE THREAD

**Issue by hbill75** [CiscoDevNet/devnet-express-cloud-collab-issues#13]
_Explore Spark Extensibility Approaches and Platforms_  section
Page 3
Proper Programming Language Push Apps

conflict with using uptime.py for the script filename and import uptime. Easy fix...name the script file anything but uptime.py. but the code challenge section is using uptime.py and anyone following it exactly will do what I did and use that filename.

error:

~/Documents/devops/devnetexpress_ext $ python3 uptime.py
Traceback (most recent call last):
  File "uptime.py", line 1, in <module>
    import requests, uptime, datetime,json
  File "/Users/stevehi/Documents/devops/devnetexpress_ext/uptime.py", line 3, in <module>
    ut = str(datetime.timedelta(seconds=uptime.uptime()))
TypeError: 'module' object is not callable

<img width="1382" alt="uptime-spark-extensibility-devnetcc" src="https://user-images.githubusercontent.com/6741265/34580052-74cee0ca-f159-11e7-9210-d75cbc57eb5e.png">

**Comment by dstaudt** [comment]
Thanks for the heads up!  Fixed via https://github.com/CiscoDevNet/devnet-express-cloud-collab/commit/1ce8c748e1432167183f7144053a1f2e8f813339
