### ISSUE TITLE
Automating Cisco Spark - Mission Module

### ISSUE THREAD

**Issue by JMac49** [CiscoDevNet/devnet-express-cloud-collab-issues#14]
Step 1. Review the code:  To add some clarity on what the students should do, you either need to add a file in the github repository for this mission or instruct the student to copy and paste the code into a new file in VS Code (or any text editor) to work with as they work through the mission.

**Comment by dstaudt** [comment]
Added new sample/fixed sample: https://github.com/CiscoDevNet/devnet-express-cloud-collab/commit/66bffe877c83d3e136b8f8b8350896db3f1b952e
