### ISSUE TITLE
Consider NodeRed to repalce Zapier

### ISSUE THREAD

**Issue by stgreenb** [CiscoDevNet/devnet-express-cloud-collab-issues#17]
I wonder if it would make sense to remove Zapier from the ipaas labs. Their UI changes often enough and there can be issues with users accounts that may be solved by moving to node red.

**Comment by ObjectIsAdvantag** [comment]
I like that idea, either host a node red instance on sandbox or run with docker.

BUT the original goal was to promote our iPaaS partners: built zapier stamplay. 

On the other hand most of these services have now limited time plans, not sure it is still a good fit for education.

**Comment by stgreenb** [comment]
> BUT the original goal was to promote our iPaaS partners: built zapier stamplay.

Although I am a huge proponent of these services, and having them have accounts on them is definitely a benefit they can go home with, my thought is that using node red would give similar "non-programming" results. With the added bonus that you could lock the version of node red so your instructions would not get out of sorts as many of those vendors often adjust their ui. Also gets rid of any user limited/expired account issues. Those other services are going to be more polished, but maybe its worth the lower troubles? Don't know, just a thought.

**Comment by dstaudt** [comment]
Interesting suggestion...
I tend to concur that we keep Zapier for now (despite the UI maintenance and subscription downsides), as much of the appeal of these services is 'you don't have to host or maintain it...it's available from anywhere via the cloud.'
A new lab showcasing using Spark with Node Red - e.g. from a local container - might be worthy.
