### ISSUE TITLE
Modifications to collab-spark-bot-hosting

### ISSUE THREAD

**Issue by stgreenb** [CiscoDevNet/devnet-express-cloud-collab-issues#18]
I am running this lab outside of the track its a part of so some of these suggestions may just clarify some items if for some reason the end-user is also running this lab outside the track. 

Step 2: 
* Add image of the forking and maybe a link to the github lab or the github forking help link: https://help.github.com/articles/fork-a-repo/
* Quickly explain that Redis is a database/storage system

Step 3: 
* SPARK_TOKEN Var: The lab does not (but it should) instruct the user to create a spark bot to generate this token. 
* PUBLIC_URL Var: You should probably indicate that if they scroll down they can cut and paste the URL (see image). 
![image](https://user-images.githubusercontent.com/18483964/36608259-501b1342-1897-11e8-9f9f-3ea3d03da63a.png)
* Minor note that the last image of this step looks nicely formatted, but the user will get the raw JSON. Not sure if that will confuse anybody.

**Comment by ObjectIsAdvantag** [comment]
Thanks for the input @stgreenb 

Is there any timeline you need that for?
Would March 14th work for you ?

**Comment by stgreenb** [comment]
@ObjectIsAdvantag , that timing will suit me just fine.

**Comment by ObjectIsAdvantag** [comment]
I've updated the lab 
- new Create Bot account step
- add image to Fork the original repo
- add Heroku domain instructions as suggested

Release v0.19.2 pushed in production
https://github.com/CiscoDevNet/labs-cloud-collab/releases/tag/v0.19.2

**Comment by ObjectIsAdvantag** [comment]
@stgreenb you'll certainly be interested to walk through ;-)
https://learninglabs.cisco.com/tracks/collab-cloud/spark-apps/collab-spark-bot-hosting/step/1

**Comment by stgreenb** [comment]
@ObjectIsAdvantag , looks good, thank you.
