### ISSUE TITLE
Module 7 : Spark bots - Improve instructions on using VSCode 

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-cloud-collab-issues#2]
- Enhance VSCode labs for accuracy/clarify
- Improve error handling/messages and/or troubleshooting guidance to handle common mistakes/issues
- [DONE] Remove Cloud9

**Comment by dstaudt** [comment]
Reviewed and updated all labs in the Spark bots module to clarify, enhance and unify instructions and guidance around using VS Code.  Modified corresponding sample code to use env variables.

Assigning Marcos for assigning reviewer, and then on to closure.
