### ISSUE TITLE
Configuring VS Code for Python

### ISSUE THREAD

**Issue by jbogarin** [CiscoDevNet/devnet-express-cloud-collab-issues#20]
In the _B - Python Programming Basics for Cloud Collab IT Pros_ on page 15 it says that you need to install the extension named Python by Don Jayamanne, however, the extension is called Python Extension Pack.

![screen shot 2018-03-21 at 1 22 22 pm](https://user-images.githubusercontent.com/4792616/37735948-29d69084-2d15-11e8-9384-67f792c942a2.png)

**Comment by dstaudt** [comment]
Thanks for reporting!
It looks like the core extension 'Python' has been taken over by Microsoft, whereas Don Jayamanne's 'Python Extension Pack' includes the core 'Python' extension as well as some other (unnecessary for this lab) extensions.
Updated text and screenshot to recommennd the Microsoft 'Python' extension, fix should appear in next publication.
