### ISSUE TITLE
bideo/sudio typo

### ISSUE THREAD

**Issue by jbogarin** [CiscoDevNet/devnet-express-cloud-collab-issues#21]
There's a typo here Experiment Audio/Video Calling & Messaging with Cisco Spark Widgets - [Add the Widget to an HTML page](https://learninglabs.cisco.com/tracks/devnet-express-cloud-collab-it-pro/business-value-itp/collab-business-sparksdk-widgets-itp/step/3) it says:

> In the previous steps, you experienced the messaging and sudio/bideo capabilities of the ‘Space’ widget in a 1:1 room.

It should say:

> In the previous steps, you experienced the messaging and audio/video capabilities of the ‘Space’ widget in a 1:1 room.

**Comment by dstaudt** [comment]
Thanks for noting, fixed and will appear in the next publish release
