### ISSUE TITLE
Requestb.in not longer available

### ISSUE THREAD

**Issue by jbogarin** [CiscoDevNet/devnet-express-cloud-collab-issues#22]
In the **collab-sparkwebhook** lab, in the [step 2](https://learninglabs.cisco.com/tracks/devnet-express-cloud-collab-it-pro/creating-spark-bots-itp/collab-sparkwebhook/step/2) the instructions ask for the student to use **requestb.in** and it is not longer available

![screen shot 2018-03-22 at 3 08 32 pm](https://user-images.githubusercontent.com/4792616/37798669-0a1935e8-2de3-11e8-9a8e-aeb24105ec67.png)

I recommend using ngrok for this part

**Comment by dstaudt** [comment]
I've migrated the lab to use the 'local inspector'ngrok web page, per your suggestion.  It would be great if you could take a quick sanity peek :)

**Comment by jbogarin** [comment]
Still some minor issues:

[Step 2](https://learninglabs.cisco.com/tracks/devnet-express-cloud-collab-it-pro/creating-spark-bots-itp/collab-sparkwebhook/step/2)

Second paragraph: As a workaround, we will use **Requestb.in**, a free online tool that functions as a "mock".

[Step 3](https://learninglabs.cisco.com/tracks/devnet-express-cloud-collab-it-pro/creating-spark-bots-itp/collab-sparkwebhook/step/3)

First paragraph: including a URL to your listening app (or in this case, **Requestb.in.)**

[Step 4](https://learninglabs.cisco.com/tracks/devnet-express-cloud-collab-it-pro/creating-spark-bots-itp/collab-sparkwebhook/step/4)

Number 2, last paragraph:  or in this case, to the **Requestb.in** URL.

ngrok image not inline

![screen shot 2018-03-22 at 7 57 42 pm](https://user-images.githubusercontent.com/4792616/37807490-59ddd49e-2e0b-11e8-8d24-dbf52c027274.png)


Other than those very small issues, it looks great.
