### ISSUE TITLE
collab-spark-extensibility-itp - powershell script doesn’t work

### ISSUE THREAD

**Issue by bjpinniger** [CiscoDevNet/devnet-express-cloud-collab-issues#23]
users were unable to get the powershell script to work on windows laptops. This was in the Explore Cisco Spark Extensibility Approaches & Platforms lab, Page 3.

**Comment by dstaudt** [comment]
Looks like Spark no longer supports TLS 1.0 connections (Powershell may default to 1.0), added a line to the script example to force TLS 1.2
