### ISSUE TITLE
Zork

### ISSUE THREAD

**Issue by jbogarin** [CiscoDevNet/devnet-express-cloud-collab-issues#25]
The Zork (adventure@sparkbot.io) is not working. It is being used in the [Spark Extensibility module](https://learninglabs.cisco.com/tracks/devnet-express-cloud-collab-it-pro/spark-extensibility-itp/collab-spark-extensibility-itp/step/4)

I think it is better to remove that step.

**Comment by dstaudt** [comment]
Replaced with Unfurl bot
Thanks!
