### ISSUE TITLE
Wrong bot addresses using old spark domain

### ISSUE THREAD

**Issue by ignaciofite** [CiscoDevNet/devnet-express-cloud-collab-issues#29]
Hello, in the following CCITPro track: https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/business-value-itp/collab-business-ciscospark-concepts-itp/step/3

several times bots have the old domain: `toFrench@sparkbot.io`, they should be updated (if this is wrong) to `ToFrench@webex.bot`.

Thanks!

This issue is also present here:
https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/business-value-itp/collab-business-ciscospark-concepts-itp/step/4

**Comment by klevenstein** [comment]
Is it safe to say that anywhere there's a lingering `sparkbot.io`, it should be changed to `webex.bot`?

**Comment by ignaciofite** [comment]
(If you're asking me:)
I was asking some colleagues that are running the event with me and yeah it seems that they should all be changed.

**Comment by klevenstein** [comment]
Okay, thanks! Easy fix; I'll get it up asap.

**Comment by klevenstein** [comment]
Fix published.

**Comment by ignaciofite** [comment]
The screenshots are still wrong, but as you mentioned in the other issue maybe this is part of a longer plan so that's not as important :)
