### ISSUE TITLE
Module 8 - Tropo labs need info on pricing and caveats

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-cloud-collab-issues#3]
- In intro content, enhance Tropo pricing and international caveats

**Comment by austinMarcos** [comment]
Marcos to assign to Phil.  Tessa can review when Phil is done.

**Comment by dstaudt** [comment]
Would like to add Steve to help/review, based on his extensive experience with this stuff, esp. international

**Comment by austinMarcos** [comment]
In weekly meeting, Phil said he would:
- upload Word document and Tessa to review
- add web site access for: David S., Tessa, and Austin

**Comment by fortunesmith** [comment]
[Module 8:Lab X - Assess Costs for Tropo.docx](https://github.com/CiscoDevNet/devnet-express-cloud-collab-issues/files/968260/Module.8.Lab.X.-.Assess.Costs.for.Tropo.docx)

First draft of the Tropo pricing lab ready for review.

**Comment by fortunesmith** [comment]
I was able to get authorization to get Steve, David, and Tessa access to the new Tropo site. Just need to gather Tropo IDs

**Comment by austinMarcos** [comment]
Need Tessa to sign off on the markdown and the content to say that this is ready to publish.

**Comment by tmero** [comment]
I had to re-review it in case there has been changes since the last time I viewed it.

Looks like the challenge was updated again and it is definitely better than the last. Thank Phil for your time on this!

Ready to Publish.

**Comment by ObjectIsAdvantag** [comment]
@klevenstein the Tropo labs have been retired and removed for the DNE-CC tracks.
I propose we close this issue.
Assigning to Karin

**Comment by klevenstein** [comment]
Closing; thanks Stève!
