### ISSUE TITLE
Wrong code on Module

### ISSUE THREAD

**Issue by ignaciofite** [CiscoDevNet/devnet-express-cloud-collab-issues#31]
Hello again (it seems that we are gonna have some conversations today haha).

More feedback, url: https://developer.cisco.com/learning/tracks/devnet-express-cloud-collab-it-pro/business-value-itp/collab-business-sparksdk-widgets-itp/step/3

Here's the code, attaching screenshot that shows in **bold** the wrong pieces.
``` html
<html>
<head>
<meta charset="utf8">
<title>Space Widget Demo</title>
<link rel="stylesheet" href="https://code.s4d.io/widget-space/production/main.css">
</head>
<body>
<div style="width: 500px; height: 500px;"
data-toggle="webex-space"
data-access-token="<your access token>"
data-destination-id="<to e-mail>"
data-destination-type="email"
/>
<script src="https://code.s4d.io/widget-space/production/bundle.js"></script>
</body>
</html>
```

![2020-04-22 15_39_31-Webex Teams](https://user-images.githubusercontent.com/15130412/79988899-7ed12380-84af-11ea-8db6-44ad2f366241.png)

The attendee also kindly suggests reviewing/updating all the documentation changing from spark to Webex 🙂, where spark was the old brand name.

Let me know if this is clear 🙂.

**Comment by klevenstein** [comment]
Yep, makes sense. Thanks! There's an overhaul in process of the collab materials, but while that's in process, we'll make these changes.

**Comment by ignaciofite** [comment]
#30 is a duplicate from another team member.

**Comment by klevenstein** [comment]
Feel free to keep raising issues - if they're easy search/replace fixes, we can at least get the text done and push those to production in the meantime.

**Comment by ignaciofite** [comment]
Will do! Thanks :)
