### ISSUE TITLE
CC issue on behalf of Markus Beer

### ISSUE THREAD

**Issue by RuthCattell** [CiscoDevNet/devnet-express-cloud-collab-issues#32]
Issue raised on behalf of Markus Beer
https://developer.cisco.com/learning/devnet-express/devnet-express-cloud-collab-it-pro/devnet-express-cloud-integration-itpro/collab-spark-zapier-itp/step/1 points to a broken link
<img width="232" alt="cc issue" src="https://user-images.githubusercontent.com/15029010/94031889-4663a780-fdb7-11ea-8e5d-ea746a08fa46.PNG">

**Comment by dstaudt** [comment]
Fixed in https://github.com/CiscoDevNet/devnet-express-cloud-collab/commit/e14dfdc2c65888d19e55736f213088c7f7e1d318
