### ISSUE TITLE
Module 2 - Business Value info needs restructuring

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-cloud-collab-issues#5]
- Target intro content at 30 min (by trimming slides)
- Add info re Tropo international caveats/pricing to intro content

**Comment by austinMarcos** [comment]
General comments from the event was that module was too long.  Not enough time on labs.  See Steve's comment:

Need an extra short lab about the Tropo pricing for international call so that devs understand how it will be priced. It is not about selling the product (sales pitch), but to make them understand how the licensing works. They would go to the pricing page, see the price per call, and price per phone number, and price per SMS, and then compute the price to create a Voice Machine in France/US/Italy depending where the lab is delivered.
This could also be explained to a participant, without them having to take the lab.

Concerning the mission, it would have needed more prep about how to run it in real time with proctors. We organized in real time to get the participants feedback. I would extend it by 10 minutes, and ensure there are enough proctors to engage the conversation with the team: 1 proctor = 3 teams maximum. Organize the team as a consequence.

**Comment by dstaudt** [comment]
From Phil:

I uploaded a new version of module 2: The Business Value of Cloud Collaboration APIs to the Box directory for Vegas; ended up trimming about 15 slides (set to hidden in the deck). I'll continue to work on the other items.

~Phil

**Comment by tmero** [comment]
I have reviewed the changes and updates. Very happy with what Phil did. IMO ready to go!

**Comment by dstaudt** [comment]
No open concerns with this module

Assigning to @klevenstein for closure
