### ISSUE TITLE
Creating Spark Bots-itp/collab-spark-apps/step/3

### ISSUE THREAD

**Issue by ctmartin** [CiscoDevNet/devnet-express-cloud-collab-issues#8]
Duplicate text on page 3/5

![duplicate text step3](https://user-images.githubusercontent.com/7167405/27131449-bcadd6b6-50d8-11e7-9758-c982cada6567.PNG)

**Comment by ctmartin** [comment]
Page 5, confusing phrasing:

Bots are dedicated Cisco Spark accounts that act under their own identity. They can be added to Rooms like any other Cisco Spark user. Some restrictions apply **_though: main of which_** happens in Group Rooms, in which bots MUST be mentioned in order to receive messages.

Should be "The main restriction happens in Group Rooms ...

**Comment by ctmartin** [comment]
Upon completion, "Go to Next Lab" pop-up takes you back to the first page of the same lab.

**Comment by dstaudt** [comment]
Fixed https://github.com/CiscoDevNet/labs-cloud-collab/commit/3b14a988209f1af27fa43b0fba6a4d487c3540fb
