### ISSUE TITLE
Creating Cisco Spark Bots

### ISSUE THREAD

**Issue by davidncsco** [CiscoDevNet/devnet-express-cloud-collab-issues#9]
General: 
       It's helpful to add "Completion Time: xx minutes" after Objective like in some labs. Currently not all labs has this.

1. Introduction to Cisco Spark Apps
        Pictures in step 1 & step 4  illustrate the same idea but are different and kind of confusing. 
           	https://learninglabs.cisco.com:8867/posts/files/collab-spark-apps/assets/images/step1-extensibility-big-picture.png
     		https://learninglabs.cisco.com:8867/posts/files/collab-spark-apps/assets/images/step4-apps.png
       
2. Experiment Cisco Spark Webhooks:
   Step 1.1 Pick a Room identifier
       the first sentence is incomplete ..."and you want..."
   Step 1.2 - "Network Administrators" room not created in any step prior to this step.
   Step 3.2 - Create a Webhook
       actual responses has a lot more fields than sample response.
{
  "id": "Y2lzY29zcGFyazovL3VzL1dFQkhPT0svZjZjZmM2MDItNmY4ZS00MzdkLTgzMWUtNzI2YmFmNWQ4NWYy",
  "name": "Spark Learning Lab Webhook",
  "targetUrl": "https://requestb.in/1deh1af1",
  "resource": "messages",
  "event": "created",
  "filter": "roomId=Y2lzY29zcGFyazovL3VzL1JPT00vYjdjNDQwYTAtNGZiMC0xMWU3LWJhNTAtMzc4ZDJlM2RkODZj",
  "orgId": "Y2lzY29zcGFyazovL3VzL09SR0FOSVpBVElPTi8xZWI2NWZkZi05NjQzLTQxN2YtOTk3NC1hZDcyY2FlMGUxMGY",
  "createdBy": "Y2lzY29zcGFyazovL3VzL1BFT1BMRS8zOTNmMWU4OC1jNmZjLTRlYWMtOTA4Mi1kNjAyMDhmZGE5NTM",
  "appId": "Y2lzY29zcGFyazovL3VzL0FQUExJQ0FUSU9OL0MyNzljYjMwYzAyOTE4MGJiNGJkYWViYjA2MWI3OTY1Y2RhMzliNjAyOTdjODUwM2YyNjZhYmY2NmM5OTllYzFm",
  "ownedBy": "creator",
  "status": "active",
  "created": "2017-06-12T23:22:30.291Z”}

3. Run a Cisco Spark Bot Locally (VS Code):
   This is a weird one. When I start debugging the debugger stops with this message:
         NameError, name 'false' is not defined
   it complains about this line in launch.json
         "stopOnEntry": false,
I had to change it to:
         "stopOnEntry": "false",
for it to start working.

When I type **MyAwesomeBot** Help me 
I got this response -> "Sorry, but I did not understand your request. Type Help me to see what I can do"

—> Debug the run_spark_bot.py script shows that in_message is ‘davidnhelp me’ so the script somehow prepended the var with my username; strange.
NOTE: This works ok if I type this directly in my bot.
Page 6:
elif in_message in expected_messages and expected_messages[in_message] is "greeting":
“greeting” should be “greetings”

**Comment by dstaudt** [comment]
1. Leaving as-is for now
2. Fixed
3. Changed to include quotes

Could not reproduce "Help me"
Page 6 "greeting" issue fixed
